import com.nmg.publisher.DataPublisherApplication;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'akampati' at '10/20/17 1:08 PM' with Gradle 3.1
 *
 * @author akampati, @date 10/20/17 1:08 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        DataPublisherApplication classUnderTest = new DataPublisherApplication();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
